#!/usr/bin/with-contenv bash
#
# Author: Major@newsmth.net, Dec, 2020
# Maintainer: Huan <zixia@zixia.net>
#

set -e

if [[ $(id -u) = 0 ]]; then
  exec s6-setuidgid bbs $0 "$@"
fi

while true; do
  echo 'bbsd service mock'
  sleep 60
done

KBS='/kbs'

function sigterm_handler () {
  echo "SIGTERM signal received, try to gracefully shutdown all services..."
  $KBS/bin/miscd flush
}

trap "sigterm_handler; exit" TERM

"$KBS"/bin/miscd daemon
"$KBS"/bin/bbslogd
"$KBS"/bin/bbsd -p 2323
"$KBS"/bin/sshbbsd -p 2222

# flush the miscd every hour
while sleep 3600; do
  "$KBS"/bin/miscd flush
done

# Wait for SIGTERM
wait
