#!/usr/bin/with-contenv bash
#
# Author: Major@newsmth.net, Dec, 2020
# Maintainer: Huan <zixia@zixia.net>
#

set -e

#
# We have initialized all bbs daemons at /etc/cont-init.d/10-daemons
#   includes: miscd, bbslogd, bbsd, sshbbsd
#

function sigterm_handler () {
  echo "SIGTERM signal received, try to gracefully shutdown all services..."
  /kbs/bin/miscd flush
}

trap "sigterm_handler; exit" TERM

# flush the miscd every hour
while sleep 3600; do
  /kbs/bin/miscd flush
done
